updated kubeflow installation script so that the helm command is idempotent (#444)
**Which issue is resolved by this Pull Request:**

running `make deploy-kubeflow` sometimes fails due to various reasons.
After fixing whatever issue that cause the failure, I am unable to run
the script again.

```
Error: INSTALLATION FAILED: cannot re-use a name that is still in use
Traceback (most recent call last):
  File "utils/kubeflow_installation.py", line 256, in <module>
    install_kubeflow(
  File "utils/kubeflow_installation.py", line 79, in install_kubeflow
    build_component(
  File "utils/kubeflow_installation.py", line 132, in build_component
    install_helm(component_name, installation_path, namespace)
  File "/Volumes/workplace/kubeflow/kubeflow-manifests/tests/e2e/utils/utils.py", line 222, in install_helm
    assert install_retcode == 0
AssertionError
make: *** [deploy-kubeflow] Error 1
```

**Description of your changes:**

Updated the helm command from `helm install` to `helm upgrade
--install`, which would run an install if a release by this name doesn't
already exist.

https://helm.sh/docs/helm/helm_upgrade/

**Testing:**
- [N.A] Unit tests pass
- [N.A] e2e tests pass
- Details about new tests (If this PR adds a new feature)
- Details about any manual tests performed

Manually tested by running `deploy-kubeflow`. Observed that installation
is successful without `Error: INSTALLATION FAILED: cannot re-use a name
that is still in use`.
 
By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.