[Bug] Helm Generator Tool Bug Fix (#580)
This fix the edge case that when there are multiple possible problem
file types/folders, moved file will need to be removed from the
candidate list to avoid file not find exception.

```
FileNotFoundError: [Errno 2] No such file or directory: './tools/helmify/generated_output/helm_chart_temp_output_files/kserve/templates/ClusterServingRuntime/inferenceservice-config-kubeflow-ConfigMap.yaml' -> './tools/helmify/generated_output/helm_chart_temp_output_files/kserve/potential_failed_helm_conversions/ClusterServingRuntime/inferenceservice-config-kubeflow-ConfigMap.yaml'
```